import type {
  Promotor,
  RotaPromotor,
  CampanhaPerguntas,
} from "./types";

export const mockPromotor: Promotor = {
  ID_PROMOTOR: 1,
  NOME: "Carlos Silva",
  EMAIL: "carlos@email.com",
  CPF: "12345678900",
  ID_CLIENT: 1,
  CREATED_BY: 1,
  CREATED_AT: new Date().toISOString(),
  UPDATED_AT: new Date().toISOString(),
};

export const mockRotas: RotaPromotor[] = [
  {
    id_rota_promotor: 1,
    id_oficina: 1,
    id_campanha_promotor: 1,
    status: "BACKLOG",
    success: null,
    checkin_time: null,
    done_at: null,
    obs: null,
    redirect: null,
    oficina: {
      id_oficina: 1,
      nome: "Auto Center Oliveira",
      endereco: "Rua das Flores, 123, Centro, Sao Paulo, SP",
      telefone: "(11) 3456-7890",
      localizacao: "-23.5505,-46.6333",
      bairro: "Centro",
      cidade: "Sao Paulo",
      estado: "SP",
      distancia_km: 1.2,
    },
    campanha: {
      id_campanha: 1,
      nome: "Campanha Oleo Premium",
      objetivo: "VENDA",
    },
  },
  {
    id_rota_promotor: 2,
    id_oficina: 2,
    id_campanha_promotor: 1,
    status: "BACKLOG",
    success: null,
    checkin_time: null,
    done_at: null,
    obs: null,
    redirect: null,
    oficina: {
      id_oficina: 2,
      nome: "Mecanica Rapida Express",
      endereco: "Av. Brasil, 456, Liberdade, Sao Paulo, SP",
      telefone: "(11) 2345-6789",
      localizacao: "-23.5575,-46.6353",
      bairro: "Liberdade",
      cidade: "Sao Paulo",
      estado: "SP",
      distancia_km: 2.8,
    },
    campanha: {
      id_campanha: 1,
      nome: "Campanha Oleo Premium",
      objetivo: "VENDA",
    },
  },
  {
    id_rota_promotor: 3,
    id_oficina: 3,
    id_campanha_promotor: 1,
    status: "BACKLOG",
    success: null,
    checkin_time: null,
    done_at: null,
    obs: null,
    redirect: null,
    oficina: {
      id_oficina: 3,
      nome: "Oficina do Joao Freios",
      endereco: "Rua Augusta, 789, Consolacao, Sao Paulo, SP",
      telefone: "(11) 1234-5678",
      localizacao: "-23.5615,-46.6553",
      bairro: "Consolacao",
      cidade: "Sao Paulo",
      estado: "SP",
      distancia_km: 4.5,
    },
    campanha: {
      id_campanha: 1,
      nome: "Campanha Oleo Premium",
      objetivo: "VENDA",
    },
  },
  {
    id_rota_promotor: 4,
    id_oficina: 4,
    id_campanha_promotor: 1,
    status: "BACKLOG",
    success: null,
    checkin_time: null,
    done_at: null,
    obs: null,
    redirect: null,
    oficina: {
      id_oficina: 4,
      nome: "Point Car Service",
      endereco: "Rua Vergueiro, 321, Vila Mariana, Sao Paulo, SP",
      telefone: "(11) 9876-5432",
      localizacao: "-23.5725,-46.6363",
      bairro: "Vila Mariana",
      cidade: "Sao Paulo",
      estado: "SP",
      distancia_km: 6.1,
    },
    campanha: {
      id_campanha: 1,
      nome: "Campanha Oleo Premium",
      objetivo: "VENDA",
    },
  },
];

export const mockPerguntas: CampanhaPerguntas[] = [
  {
    id_perguntas: "q1",
    id_campanha: "c1",
    pergunta: "Qual a quantidade de oleo em estoque?",
    tipo: "NUMERO",
  },
  {
    id_perguntas: "q2",
    id_campanha: "c1",
    pergunta: "O material promocional foi instalado?",
    tipo: "SIM_NAO",
  },
  {
    id_perguntas: "q3",
    id_campanha: "c1",
    pergunta: "Como esta a exposicao dos produtos?",
    tipo: "TEXTO",
  },
  {
    id_perguntas: "q4",
    id_campanha: "c1",
    pergunta: "O responsavel da oficina estava presente?",
    tipo: "SIM_NAO",
  },
];
